baseURL = "https://blog.jinreal.com/"
languageCode = "zh-cn"
title = "牛津的博客"
theme = 'noteworthy-mod'

[params]
    # Programming
    github = "github.com/jinreal/"
    weibo = "weibo.com/jinreal2014"
    medium = "medium.com/@tech3e"