baseURL = "https://blog.jinreal.com/"
languageCode = "zh-cn"
title = "牛津的博客"
theme = 'noteworthy-mod'

[params]
    # Programming
    github = "https://github.com/jinreal/"
    weibo = "http://weibo.com/jinreal2014"
    medium = "https://medium.com/@tetconst"

[taxonomies]
  tag = "tags"

[[menu.main]]
	identifier = "tags"
	name = "標籤"
	url = "/tags/"
	weight = 2

[[menu.main]]
	identifier = "tags-novel"
	name = "小說"
	url = "/tags/小說/"
	weight = 2